CREATE TYPE "OrderStatus" AS ENUM ('PENDING_REVIEW', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');
ALTER TABLE "SoOrder" ADD COLUMN "status" "OrderStatus" NOT NULL DEFAULT 'PENDING_REVIEW';
CREATE INDEX "SoOrder_status_idx" ON "SoOrder"("status");
