import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { currentUser } from "@/lib/auth";
import { actorFields } from "@/lib/audit";
import { assertTransportStatusTransition } from "@/lib/transport-status";
const text=z.string().trim().max(500).optional();const date=z.string().datetime().optional();
const schema=z.object({status:z.enum(["PLANNED","DISPATCHED","IN_TRANSIT","COMPLETED","CANCELLED"]),vehicleNo:text, fleetOwnerName:text,driverName:text,driverPhone:text,pickupTerminal:text,factoryLocation:text,returnTerminal:text,plannedPickupAt:date,actualPickupAt:date,actualFactoryArrivedAt:date,actualReturnAt:date,trailerSwapNote:text,overnightNote:text,exceptionNote:text,note:text});
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const input=schema.safeParse(await request.json());if(!input.success)return NextResponse.json({error:"运输状态资料无效"},{status:400});const actor=await currentUser();if(!actor)return NextResponse.json({error:"请先登录"},{status:401});const {id}=await params;try{const task=await prisma.$transaction(async tx=>{const current=await tx.transportTask.findUnique({where:{id},include:{legs:{orderBy:{sequence:"asc"},take:1}}});if(!current)throw new Error("运输任务不存在");assertTransportStatusTransition(current.status,input.data.status);const now=new Date();const updated=await tx.transportTask.update({where:{id},data:{status:input.data.status,dispatchedAt:input.data.status==="DISPATCHED"?now:current.dispatchedAt,completedAt:input.data.status==="COMPLETED"?now:current.completedAt,note:input.data.note??current.note}});if(current.legs[0]){const {plannedPickupAt,actualPickupAt,actualFactoryArrivedAt,actualReturnAt,...leg}=input.data;await tx.transportLeg.update({where:{id:current.legs[0].id},data:{...leg,status:input.data.status,plannedPickupAt:plannedPickupAt?new Date(plannedPickupAt):undefined,actualPickupAt:actualPickupAt?new Date(actualPickupAt):undefined,actualFactoryArrivedAt:actualFactoryArrivedAt?new Date(actualFactoryArrivedAt):undefined,actualReturnAt:actualReturnAt?new Date(actualReturnAt):undefined}});}await tx.operationLog.create({data:{action:"TRANSPORT_TASK_STATUS_CHANGED",entityType:"TransportTask",entityId:id,...actorFields(actor),before:{status:current.status},after:input.data}});return updated;});return NextResponse.json(task);}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"运输状态更新失败"},{status:409});}}
