import {readFile} from "node:fs/promises";
import {join} from "node:path";
import {PDFParse} from "pdf-parse";
import {PrismaClient} from "@prisma/client";
import {ParserRegistry} from "../src/lib/so-parser";
import {resolveSiCutoff} from "../src/lib/si-cutoff";
const db=new PrismaClient();
const fields=["soNumber","carrier","customerReference","vesselName","voyage","loadPort","dischargePort","etdText","etaText","cutoffText","openingText","vgmCutoffText","portCutoffText","emptyPickupLocation","fullReturnLocation","transportMode","siCutoffText"] as const;
async function main(){const root=process.env.FILE_STORAGE_ROOT||"./uploads";const files=await db.soFileVersion.findMany({where:{parseStatus:"PENDING"},include:{soOrder:{include:{containers:true}}}});let processedCount=0,failedCount=0;for(const file of files){try{const pdf=new PDFParse({data:await readFile(join(root,file.storageKey))});const result=await pdf.getText();await pdf.destroy();const parsed=new ParserRegistry().parse({fileName:file.originalName,text:result.text});const siCutoff=resolveSiCutoff({originalSiText:parsed.siCutoffText,latestDeadlineText:parsed.cutoffText,otherCutoffTexts:[parsed.portCutoffText,parsed.vgmCutoffText]});const extraction={...parsed,siCutoff,raw:{...parsed.raw,extractedText:result.text}};const order=file.soOrder;if(!order)throw new Error("文件未关联 SO");const changes:Record<string,unknown>=Object.fromEntries(fields.filter(key=>parsed[key]!==undefined&&parsed[key]!==order[key]).map(key=>[key,{from:order[key],to:parsed[key]}]));const oldTypes=order.containers.reduce<Record<string,number>>((a,c)=>({...a,[c.containerType]:(a[c.containerType]||0)+1}),{});const newTypes=parsed.containers.reduce<Record<string,number>>((a,c)=>({...a,[c.containerType]:(a[c.containerType]||0)+c.quantity}),{});if(JSON.stringify(oldTypes)!==JSON.stringify(newTypes))changes.containers={from:oldTypes,to:newTypes};await db.$transaction(async tx=>{await tx.soFileVersion.update({where:{id:file.id},data:{parseStatus:"PARSED",rawExtraction:extraction as object}});if(order.parseStatus==="VERIFIED"){if(Object.keys(changes).length)await tx.soVersionChange.create({data:{soOrderId:order.id,soFileVersionId:file.id,changes}});}else{const data=Object.fromEntries(fields.filter(key=>parsed[key]!==undefined&&parsed[key]!==null&&parsed[key]!=="").map(key=>[key,parsed[key]]));await tx.soOrder.update({where:{id:order.id},data:{...data,siCutoffText:siCutoff.effectiveText||null,siCutoffSource:siCutoff.source,siCutoffOriginalText:siCutoff.originalText||null,siCutoffEstimatedFromText:siCutoff.estimatedFromText||null,parseStatus:"PARSED"}});}await tx.operationLog.create({data:{action:"SO_PARSED",entityType:"SoOrder",entityId:order.id,after:{fileVersion:file.version,changes,siCutoff}}});});processedCount++;}catch(error){failedCount++;await db.soFileVersion.update({where:{id:file.id},data:{parseStatus:"FAILED"}});console.error(`failed ${file.originalName}`,error)}}console.log(`PARSE_SUMMARY=${JSON.stringify({processedCount,failedCount})}`)}main().finally(()=>db.$disconnect());
